const phrases = [
        'Hello! Bonjour!',
        'How are you? Comment ça va?',
        'What is your name? Comment tu t\'appelles?',
        'Good morning! Bonjour!',
        'Good night! Bonne nuit!',
        'Please. S\'il vous plaît.',
        'Thank you! Merci!',
        'Excuse me. Excusez-moi.',
        'I like pizza. J\'aime la pizza.',
        'Let\'s play! Jouons!',
        'Goodbye! Au revoir!',
        'My favorite color is blue. Ma couleur préférée est le bleu.',
        'Can I have a cookie? Puis-je avoir un biscuit?',
        'I love animals. J\'adore les animaux.',
        'It\'s time for bed. Il est l\'heure d\'aller au lit.',
        'What day is it today? Quel jour sommes-nous aujourd\'hui?',
        'I can count to ten. Je sais compter jusqu\'à dix.',
        'What\'s the weather like today? Quel temps fait-il aujourd\'hui?',
        'I have a pet cat. J\'ai un chat comme animal de compagnie.',
        'I want to learn new things. Je veux apprendre de nouvelles choses.',
        'Can I help you? Puis-je t\'aider?',
        'I need a pencil. J\'ai besoin d\'un crayon.',
        'I\'m thirsty. J\'ai soif.',
        'Can we go to the park? Pouvons-nous aller au parc?',
        'Look at the beautiful flowers. Regarde les belles fleurs.',
        'I\'m hungry. J\'ai faim.',
        'What\'s your favorite book? Quel est ton livre préféré?',
        'I can tie my shoes. Je sais attacher mes lacets.',
        'What\'s that? Qu\'est-ce que c\'est?',
        'I have a big family. J\'ai une grande famille.',
        'Can I have some juice? Puis-je avoir du jus?',
        'I\'m happy. Je suis heureux(se).',
        'Can we go for a walk? Pouvons-nous aller nous promener?',
        'I don\'t understand. Je ne comprends pas.',
        'Can you sing a song? Peux-tu chanter une chanson?',
        'I like to draw. J\'aime dessiner.',
        'What\'s your favorite animal? Quel est ton animal préféré?',
        'I can ride my bike. Je sais faire du vélo.',
        'What\'s your favorite subject? Quelle est ta matière préférée?',
        'I have a little brother. J\'ai un petit frère.',
        'Can you say "hello" in French? Peux-tu dire "bonjour" en français?',
        'I\'m tired. Je suis fatigué(e).',
        'Can we play a game? Pouvons-nous jouer à un jeu?',
        'I like to play with my toys. J\'aime jouer avec mes jouets.',
        'What color is the sky? De quelle couleur est le ciel?',
        'I can write my name. Je sais écrire mon nom.',
        'I\'m excited. Je suis excité(e).',
        'Can I have a hug? Puis-je avoir un câlin?',
        'I have a best friend. J\'ai un meilleur ami / une meilleure amie.',
        'What\'s for lunch? Qu\'y a-t-il pour le déjeuner?',
        'I\'m sorry. Je suis désolé(e).',
        'Can you show me how to do it? Peux-tu me montrer comment faire?',
        'I have a yellow balloon. J\'ai un ballon jaune.',
        'What\'s the time? Quelle heure est-il?',
        'I\'m cold. J\'ai froid.',
        'Can we make a craft? Pouvons-nous faire un bricolage?',
        'I like to dance. J\'aime danser.',
        'What\'s your favorite color? Quelle est ta couleur préférée?',
        'I can read a book. Je sais lire un livre.',
        'Can I have some popcorn? Puis-je avoir du pop-corn?',
        'I have a green backpack. J\'ai un sac à dos vert.',
        'What\'s your favorite season? Quelle est ta saison préférée?',
        'I like to play hide and seek. J\'aime jouer à cache-cache.',
        'Can I have a sticker? Puis-je avoir un autocollant?',
        'I have a blue umbrella. J\'ai un parapluie bleu.',
        'What\'s your favorite movie? Quel est ton film préféré?',
        'I\'m hot. J\'ai chaud.',
        'Can we go to the zoo? Pouvons-nous aller au zoo?',
        'I like to build with blocks. J\'aime construire avec des blocs.',
        'What\'s your favorite song? Quelle est ta chanson préférée?',
        'I have a red car. J\'ai une voiture rouge.',
        'Can I have a high-five? Puis-je avoir un "high-five"?',
        'I\'m proud of you. Je suis fier / fière de toi.',
        'Can we plant flowers? Pouvons-nous planter des fleurs?',
        'I like to jump. J\'aime sauter.',
        'What\'s your favorite food? Quel est ton plat préféré?',
        'I have a purple shirt. J\'ai une chemise violette.',
        'Can I have a piece of cake? Puis-je avoir un morceau de gâteau?',
        'I\'m sleepy. J\'ai sommeil.',
        'Can we have a tea party? Pouvons-nous faire une fête du thé?',
        'I like to play with puzzles. J\'aime jouer avec des puzzles.',
        'What\'s your favorite toy? Quel est ton jouet préféré?',
        'I have a big family. J\'ai une grande famille.',
        'Can I have a turn? Puis-je jouer à mon tour?',
        'I\'m so happy. Je suis tellement heureux(se).',
        'Can we go to the beach? Pouvons-nous aller à la plage?',
        'I like to help. J\'aime aider.',
        'What\'s your favorite book series? Quelle est ta série de livres préférée?',
        'I have a brown teddy bear. J\'ai un ours en peluche marron.',
        'Can we have a dance party? Pouvons-nous faire une fête dansante?',
        'Can we go for a bike ride? Pouvons-nous faire du vélo?',
        'I have a yellow duck. J\'ai un canard jaune.',
        'What\'s your favorite ice cream flavor? Quel est ton parfum de glace préféré?',
        'I like to play with my dolls. J\'aime jouer avec mes poupées.',
        'Can I have a sandwich for lunch? Puis-je avoir un sandwich pour le déjeuner?',
        'I\'m going to the park. Je vais au parc.',
        'What\'s your favorite holiday? Quelle est ta fête préférée?',
        'I have a big smile. J\'ai un grand sourire.',
        'Can we visit grandma and grandpa? Pouvons-nous rendre visite à mamie et papy?',
        'I like to draw with crayons. J\'aime dessiner avec des crayons de couleur.',
        'Can I have a piece of chocolate? Puis-je avoir un morceau de chocolat?',
        'I\'m feeling silly. Je me sens bête.',
        'What\'s your favorite subject in school? Quelle est ta matière préférée à l\'école?',
        'I have a green frog. J\'ai une grenouille verte.',
        'Can we have a movie night? Pouvons-nous avoir une soirée cinéma?',
        'Can we go for a bike ride? Pouvons-nous faire du vélo?',
        'I have a yellow duck. J\'ai un canard jaune.',
        'What\'s your favorite ice cream flavor? Quel est ton parfum de glace préféré?',
        'I like to play with my dolls. J\'aime jouer avec mes poupées.',
        'Can I have a sandwich for lunch? Puis-je avoir un sandwich pour le déjeuner?',
        'I\'m going to the park. Je vais au parc.',
        'What\'s your favorite holiday? Quelle est ta fête préférée?',
        'I have a big smile. J\'ai un grand sourire.',
        'Can we visit grandma and grandpa? Pouvons-nous rendre visite à mamie et papy?',
        'I like to draw with crayons. J\'aime dessiner avec des crayons de couleur.',
        'Can I have a piece of chocolate? Puis-je avoir un morceau de chocolat?',
        'I\'m feeling silly. Je me sens bête.',
        'What\'s your favorite subject in school? Quelle est ta matière préférée à l\'école?',
        'I have a green frog. J\'ai une grenouille verte.',
        'Can we have a movie night? Pouvons-nous avoir une soirée cinéma?',
        'I like to play with my toy train. J\'aime jouer avec mon train en jouet.',
        'What\'s your favorite thing to do at the playground? Quelle est ta chose préférée à faire au terrain de jeux?',
        'I have a pink backpack. J\'ai un sac à dos rose.',
        'Can I have a bedtime story? Puis-je avoir une histoire avant de dormir?',
        'I\'m good at playing soccer. Je suis doué(e) pour jouer au soccer.',
        'What\'s your favorite bedtime routine? Quelle est ta routine du coucher préférée?',
        'I have a blue dolphin. J\'ai un dauphin bleu.',
        'Can we have a family game night? Pouvons-nous avoir une soirée jeux en famille?',
        'I like to play with my action figures. J\'aime jouer avec mes figurines d\'action.',
        'What\'s your favorite thing to do on a rainy day? Quelle est ta chose préférée à faire par temps de pluie?',
        'I have a purple kite. J\'ai un cerf-volant violet.',
        'Can I have a banana for a snack? Puis-je avoir une banane pour une collation?',
        'I\'m going to visit my friends. Je vais rendre visite à mes amis.',
        'What\'s your favorite fruit smoothie? Quelle est ta smoothie aux fruits préférée?',
        'I like to play with my toy car. J\'aime jouer avec ma voiture en jouet.',
        'Can we have a pajama day? Pouvons-nous avoir une journée pyjama?',
        'I have a red apple. J\'ai une pomme rouge.',
        'What\'s your favorite sport to watch? Quel est ton sport préféré à regarder?',
        'I like to play with building blocks. J\'aime jouer avec des blocs de construction.',
        'Can I have a glass of milk? Puis-je avoir un verre de lait?',
        'I\'m going to a birthday party. Je vais à une fête d\'anniversaire.',
        'What\'s your favorite bedtime snack? Quelle est ta collation préférée avant de dormir?',
        'I have a yellow school bus. J\'ai un bus scolaire jaune.',
        'Can we have a teddy bear picnic? Pouvons-nous avoir un pique-nique avec des ours en peluche?',
        'I like to play with my toy kitchen. J\'aime jouer avec ma cuisine en jouet.',
        'What\'s your favorite subject in art class? Quelle est ta matière préférée en cours d\'art?',
        'I have a brown monkey. J\'ai un singe brun.',
        'Can I have a piece of watermelon? Puis-je avoir un morceau de pastèque?',
        'I\'m going to a playdate. Je vais à un rendez-vous de jeu.',
        'What\'s your favorite vegetable? Quel est ton légume préféré?',
        'I like to play with my toy plane. J\'aime jouer avec mon avion en jouet.',
        'Can we have a nature scavenger hunt? Pouvons-nous faire une chasse au trésor dans la nature?',
        'I have a green grasshopper. J\'ai une sauterelle verte.',
        'Can I have a piece of pizza? Puis-je avoir une part de pizza?',
        'I like to play with my toy robot. J\'aime jouer avec mon robot en jouet.',
        'What\'s your favorite outdoor activity? Quelle est ton activité extérieure préférée?',
        'I have a blue butterfly. J\'ai un papillon bleu.',
        'Can we have a music sing-along? Pouvons-nous avoir une séance de chant musical?',
        'I like to play with my toy rocket. J\'aime jouer avec ma fusée en jouet.',
        'What\'s your favorite thing to do at the beach? Quelle est ta chose préférée à faire à la plage?',
        'I have a pink pig. J\'ai un cochon rose.',
        'Can I have a chocolate chip cookie? Puis-je avoir un biscuit aux pépites de chocolat?',
        'I\'m going to a sleepover. Je vais à une soirée pyjama.',
        'What\'s your favorite flavor of yogurt? Quelle est ta saveur de yaourt préférée?',
        'I like to play with my toy submarine. J\'aime jouer avec mon sous-marin en jouet.',
        'Can we have a family bike ride? Pouvons-nous faire une balade à vélo en famille?',
        'I have a purple flower. J\'ai une fleur violette.',
        'Can I have a piece of birthday cake? Puis-je avoir une part de gâteau d\'anniversaire?',
        'I like to play with my toy telescope. J\'aime jouer avec ma lunette astronomique en jouet.',
        'What\'s your favorite thing to do in the snow? Quelle est ta chose préférée à faire dans la neige?',
        'I have a red ladybug. J\'ai une coccinelle rouge.',
        'Can I have a piece of pie? Puis-je avoir une part de tarte?',
        'I\'m going to a carnival. Je vais à une fête foraine.',
        'What\'s your favorite board game? Quel est ton jeu de société préféré?',
        'I like to play with my toy tractor. J\'aime jouer avec mon tracteur en jouet.',
        'Can we have a family hike? Pouvons-nous faire une randonnée en famille?',
        'I have a yellow sunflower. J\'ai un tournesol jaune.',
        'Can I have a jelly sandwich for lunch? Puis-je avoir un sandwich à la gelée pour le déjeuner?',
        'I like to play with my toy dinosaur. J\'aime jouer avec mon dinosaure en jouet.',
        'What\'s your favorite thing to do at the park? Quelle est ta chose préférée à faire au parc?',
        'I have a green turtle. J\'ai une tortue verte.',
        'Can I have a piece of candy? Puis-je avoir un bonbon?',
        'I\'m going to a costume party. Je vais à une fête déguisée.',
        'What\'s your favorite thing to do on a sunny day? Quelle est ta chose préférée à faire par une journée ensoleillée?',
        'I like to play with my toy guitar. J\'aime jouer avec ma guitare en jouet.',
        'Can we have a family movie night? Pouvons-nous avoir une soirée cinéma en famille?',
        'I have a blue whale. J\'ai une baleine bleue.',
        'Can I have a piece of chocolate cake? Puis-je avoir une part de gâteau au chocolat?',
        'I like to play with my toy spaceship. J\'aime jouer avec ma navette spatiale en jouet.',
        'What\'s your favorite thing to do in the garden? Quelle est ta chose préférée à faire dans le jardin?',
        'I have a yellow school bus. J\'ai un bus scolaire jaune.',
        'Can I have a peanut butter and jelly sandwich? Puis-je avoir un sandwich au beurre de cacahuète et à la gelée?',
        'I\'m going to a play. Je vais à une pièce de théâtre.',
        'What\'s your favorite type of sandwich? Quel est ton type de sandwich préféré?',
        'I like to play with my toy helicopter. J\'aime jouer avec mon hélicoptère en jouet.',
        'Can we have a family picnic? Pouvons-nous avoir un pique-nique en famille?',
        'I have a pink flamingo. J\'ai un flamant rose.',
        'Can I have a piece of apple pie? Puis-je avoir une part de tarte aux pommes?',
        'I\'m going to a museum. Je vais à un musée.',
        'What\'s your favorite thing to do at a birthday party? Quelle est ta chose préférée à faire lors d\'une fête d\'anniversaire?',
        'I like to play with my toy boat. J\'aime jouer avec mon bateau en jouet.',
        'Can we have a family game day? Pouvons-nous avoir une journée jeux en famille?',
        'I have a green caterpillar. J\'ai une chenille verte.',
        'Can I have a piece of watermelon cake? Puis-je avoir une part de gâteau à la pastèque?',
        'I\'m going to a zoo. Je vais au zoo.',
        'Can I have a cheese sandwich for lunch? Puis-je avoir un sandwich au fromage pour le déjeuner?',
        'I like to play with my toy horse. J\'aime jouer avec mon cheval en jouet.',
        'What\'s your favorite thing to do in the summer? Quelle est ta chose préférée à faire en été?',
        'I have a blue elephant. J\'ai un éléphant bleu.',
        'Can I have a piece of strawberry cake? Puis-je avoir une part de gâteau à la fraise?',
        'I\'m going to a friend\'s birthday party. Je vais à la fête d\'anniversaire d\'un ami.',
        'What\'s your favorite thing to do in the fall? Quelle est ta chose préférée à faire en automne?',
        'I like to play with my toy truck. J\'aime jouer avec mon camion en jouet.',
        'Can we have a family craft day? Pouvons-nous avoir une journée bricolage en famille?',
        'I have a purple butterfly. J\'ai un papillon violet.',
        'Can I have a piece of blueberry pie? Puis-je avoir une part de tarte aux myrtilles?',
        'I\'m going to a science museum. Je vais à un musée des sciences.',
        'What\'s your favorite thing to do in the winter? Quelle est ta chose préférée à faire en hiver?',
        'I like to play with my toy car. J\'aime jouer avec ma voiture en jouet.',
        'Can we have a family nature walk? Pouvons-nous faire une promenade nature en famille?',
        'I have a yellow giraffe. J\'ai une girafe jaune.',
        'Can I have a piece of cherry pie? Puis-je avoir une part de tarte à la cerise?',
        'I\'m going to a circus. Je vais à un cirque.',
        'What\'s your favorite thing to do in the spring? Quelle est ta chose préférée à faire au printemps?',
        'I like to play with my toy submarine. J\'aime jouer avec mon sous-marin en jouet.',
        'Can we have a family art day? Pouvons-nous avoir une journée artistique en famille?',
        'I have a pink unicorn. J\'ai une licorne rose.',
        'Can I have a piece of lemon cake? Puis-je avoir une part de gâteau au citron?',
        'I\'m going to a farm. Je vais à une ferme.',
        'What\'s your favorite thing to do on a cloudy day? Quelle est ta chose préférée à faire par temps nuageux?',
        'I like to play with my toy spaceship. J\'aime jouer avec ma navette spatiale en jouet.',
        'Can we have a family cooking day? Pouvons-nous avoir une journée cuisine en famille?',
        'I have a green dragonfly. J\'ai une libellule verte.',
        'Can I have a piece of peach pie? Puis-je avoir une part de tarte à la pêche?',
        'I\'m going to a zoo. Je vais au zoo.',
        'What\'s your favorite thing to do on a windy day? Quelle est ta chose préférée à faire par temps venteux?',
        'I like to play with my toy robot. J\'aime jouer avec mon robot en jouet.',
        'Can we have a family reading day? Pouvons-nous avoir une journée lecture en famille?',
        'I have a red ladybug. J\'ai une coccinelle rouge.',
        'Can I have a piece of pumpkin pie? Puis-je avoir une part de tarte à la citrouille?',
        'I\'m going to a beach. Je vais à une plage.',
        'What\'s your favorite thing to do on a sunny day? Quelle est ta chose préférée à faire par une journée ensoleillée?',
        'I like to play with my toy guitar. J\'aime jouer avec ma guitare en jouet.',
        'Can we have a family bike ride? Pouvons-nous faire une balade à vélo en famille?',
        'I have a blue whale. J\'ai une baleine bleue.',
        'Can I have a peanut butter and jelly sandwich? Puis-je avoir un sandwich au beurre de cacahuète et à la gelée?',
        'I\'m going to a play. Je vais à une pièce de théâtre.',
        'What\'s your favorite type of sandwich? Quel est ton type de sandwich préféré?',
        'I like to play with my toy helicopter. J\'aime jouer avec mon hélicoptère en jouet.',
        'Can we have a family game day? Pouvons-nous avoir une journée jeux en famille?',
        'I have a green caterpillar. J\'ai une chenille verte.',
        'Can I have a piece of watermelon cake? Puis-je avoir une part de gâteau à la pastèque?',
        'I\'m going to a zoo. Je vais au zoo.',
        'What\'s your favorite thing to do in the garden? Quelle est ta chose préférée à faire dans le jardin?',
        'I have a yellow school bus. J\'ai un bus scolaire jaune.',
        'Can I have a peanut butter and jelly sandwich? Puis-je avoir un sandwich au beurre de cacahuète et à la gelée?',
        'I\'m going to a play. Je vais à une pièce de théâtre.',
        'What\'s your favorite type of sandwich? Quel est ton type de sandwich préféré?',
        'I like to play with my toy helicopter. J\'aime jouer avec mon hélicoptère en jouet.',
        'Can we have a family game day? Pouvons-nous avoir une journée jeux en famille?',
        'I have a green caterpillar. J\'ai une chenille verte.',
        'Can I have a piece of watermelon cake? Puis-je avoir une part de gâteau à la pastèque?',
        'I\'m going to a zoo. Je vais au zoo.',
        'What\'s your favorite thing to do in the garden? Quelle est ta chose préférée à faire dans le jardin?',
        'I have a yellow school bus. J\'ai un bus scolaire jaune.',
        'Can I have a peanut butter and jelly sandwich? Puis-je avoir un sandwich au beurre de cacahuète et à la gelée?',
        'I\'m going to a play. Je vais à une pièce de théâtre.',
        'What\'s your favorite type of sandwich? Quel est ton type de sandwich préféré?',
        'I like to play with my toy helicopter. J\'aime jouer avec mon hélicoptère en jouet.',
        'Can we have a family game day? Pouvons-nous avoir une journée jeux en famille?',
        'I have a green caterpillar. J\'ai une chenille verte.',
        'Can I have a piece of watermelon cake? Puis-je avoir une part de gâteau à la pastèque?',
        'I\'m going to a zoo. Je vais au zoo.',
        'What\'s your favorite thing to do in the garden? Quelle est ta chose préférée à faire dans le jardin?',
        'I have a yellow school bus. J\'ai un bus scolaire jaune.',
        'Can I have a peanut butter and jelly sandwich? Puis-je avoir un sandwich au beurre de cacahuète et à la gelée?',
        'I\'m going to a play. Je vais à une pièce de théâtre.',
        'What\'s your favorite type of sandwich? Quel est ton type de sandwich préféré?',
        'Good afternoon! Bon après-midi!',
        'How\'s the weather today? Comment est le temps aujourd\'hui?',
        'Can you pass me the salt? Peux-tu me passer le sel?',
        'Nice to meet you! Enchanté(e)!',
        'See you later! À plus tard!',
        'I need a cup of coffee. J\'ai besoin d\'une tasse de café.',
        'Do you like to read? Est-ce que tu aimes lire?',
        'What\'s your favorite movie genre? Quel est ton genre de film préféré?',
        'I have a green backpack. J\'ai un sac à dos vert.',
        'Can we go for a swim? Pouvons-nous aller nager?',
        'I enjoy cooking. J\'aime cuisiner.',
        'What\'s your dream vacation destination? Quelle est ta destination de vacances de rêve?',
        'I\'m going to a concert. Je vais à un concert.',
        'Can you help me with my homework? Peux-tu m\'aider avec mes devoirs?',
        'I have a yellow umbrella. J\'ai un parapluie jaune.',
        'What\'s your favorite type of music? Quel est ton genre de musique préféré?',
        'I love hiking. J\'adore faire de la randonnée.',
        'Can we have a family game night? Pouvons-nous avoir une soirée jeux en famille?',
        'I enjoy playing chess. J\'aime jouer aux échecs.',
        'What\'s your favorite type of pizza? Quel est ton type de pizza préféré?',
        'I`\'m going to the gym. Je vais à la salle de sport.',
        'Can you speak another language? Peux-tu parler une autre langue?',
        'I have a purple backpack. J\'ai un sac à dos violet.',
        'What\'s your favorite board game? Quel est ton jeu de société préféré?',
        'I like to paint. J\'aime peindre.',
        'Can we have a family movie night? Pouvons-nous avoir une soirée cinéma en famille?',
        'I have a blue dolphin. J\'ai un dauphin bleu.',
        'What\'s your favorite hobby? Quel est ton passe-temps préféré?',
        'I\'m going to a dance class. Je vais à un cours de danse.',
        'Can I have a piece of chocolate cake? Puis-je avoir une part de gâteau au chocolat?',
        'Good evening! Bonsoir!',
        'Did you enjoy the movie? As-tu aimé le film?',
        'I\'m craving ice cream. J\'ai envie de crème glacée.',
        'Have you ever traveled abroad? As-tu déjà voyagé à l\'étranger?',
        'Let\'s go for a bike ride! Allons faire du vélo!',
        'I\'m learning to play the guitar. J\'apprends à jouer de la guitare.',
        'Can you recommend a good book? Peux-tu recommander un bon livre?',
        'What\'s your favorite type of cuisine? Quel est ton type de cuisine préféré?',
        'I have a pink backpack. J\'ai un sac à dos rose.',
        'Do you like to dance? Aimes-tu danser?',
        'I\'m planning a picnic. Je prévois un pique-nique.',
        'What\'s your favorite art form? Quelle est ta forme d\'art préférée?',
        'I enjoy stargazing. J\'aime observer les étoiles.',
        'Can you play a musical instrument? Sais-tu jouer d\'un instrument de musique?',
        'I have a yellow umbrella. J\'ai un parapluie jaune.',
        'Have you ever tried sushi? As-tu déjà essayé les sushis?',
        'I love going to the beach. J\'adore aller à la plage.',
        'Can we have a family game night? Pouvons-nous avoir une soirée jeux en famille?',
        'I\'m passionate about photography. Je suis passionné(e) par la photographie.',
        'What\'s your favorite type of dessert? Quel est ton dessert préféré?',
        'I\'m going to a yoga class. Je vais à un cours de yoga.',
        'Do you enjoy gardening? Aimes-tu jardiner?',
        'I have a blue dolphin. J\'ai un dauphin bleu.',
        'Can you juggle? Sais-tu jongler?',
        'I like to explore new places. J\'aime explorer de nouveaux endroits.',
        'Can we have a family movie night? Pouvons-nous avoir une soirée cinéma en famille?',
        'I have a green thumb. J\'ai la main verte.',
        'What\'s your favorite type of flower? Quel est ton type de fleur préféré?',
        'I\'m going to a comedy show. Je vais à un spectacle de comédie.',
        'Can I have a piece of chocolate cake? Puis-je avoir une part de gâteau au chocolat?',
        'I like to play with my toy helicopter. J\'aime jouer avec mon hélicoptère en jouet.'];
      
  let currentPhraseIndex = 0;
  
  function nextPhrase() {
    const phraseElement = document.getElementById('phrase');
    phraseElement.textContent = phrases[currentPhraseIndex];
    
    currentPhraseIndex++;
    if (currentPhraseIndex === phrases.length) {
      currentPhraseIndex = 0;
    }
  }
  
  nextPhrase(); // Affiche la première phrase au chargement de la page